language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: b289f6a583da1427c25bcfb7fba68811c74ac6c1
  local_dir: docs
  target_branch: gh-pages
  on:
    branch: master