# Setup
title:               Zemian's Blog
tagline:             'Life in programming world!'
description:         'A weblog on software development.'
url:                 https://zemian.github.io
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Zemian Deng
  url:               https://twitter.com/zemiandeng
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
google_analytics_id: UA-135626598-1

# Build
destination: docs
